# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1934077662d95cdf69891ef1e5e492dd0b057561f5bf8cd21376badc589d140710580159da362f7d63ec06128aaf3fdc6c69cee96c21db90515acfb7ec6cdd4

test:
  secret_key_base: b3f16867680816840797d108b1f0157398dc1eed2364c91190ca7beb47c0e9a1f12762a72c9ec45fb84db592c30fd846db4e70cb95b41a633822cadeb9025cc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
